# Changes will be applied only after server restart
[command]
base = "proxylist"
detailed = "detailed"

# Details for connecting to Redis DB
# Changes will be applied only after server restart
[connection]
host = "url-without-http/s-here"
port = 1111
user = "default"
password = "password123"

# List command formatting using MiniMessage
# Changes will be applied after config reload
[format]
# Name of the proxy in separated command
# Supports MiniMessage
name = "<gold>ChangeThisProxyNameInConfig</gold>"
simple = "<gold>Online Players: </gold> <aqua><online_players></aqua>"
detailed = "<proxy_name> <gold>: </gold> <aqua><online_players></aqua>"